/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package businessmanagement.userInterface;

import businessmanagement.Business.Business;
import businessmanagement.MarketModel.Channel;
import businessmanagement.MarketModel.Market;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 43999
 */
public class ChannelListPane extends javax.swing.JPanel {

    /**
     * Creates new form ChannelListPane
     */
    Business business;
    public ChannelListPane(Business b) {
        initComponents();
        business = b;
        Populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RightPane = new javax.swing.JPanel();
        ChannelListLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ChannelTable = new javax.swing.JTable();
        ChannelLabel1 = new javax.swing.JLabel();
        ChannelNameText = new javax.swing.JTextField();
        ChannelAddButton = new javax.swing.JButton();
        ChannelSearchButton = new javax.swing.JButton();
        ChannelLabel2 = new javax.swing.JLabel();
        ChannelSearchText = new javax.swing.JTextField();
        ChannelDeleteButton = new javax.swing.JButton();
        ChannelRefreshButton1 = new javax.swing.JButton();

        ChannelListLabel.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        ChannelListLabel.setText("Channel List");

        ChannelTable.setAutoCreateRowSorter(true);
        ChannelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Channel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ChannelTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(ChannelTable);

        ChannelLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        ChannelLabel1.setText("Add a Channel: ");

        ChannelNameText.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        ChannelNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChannelNameTextActionPerformed(evt);
            }
        });

        ChannelAddButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        ChannelAddButton.setText("Add");
        ChannelAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChannelAddButtonActionPerformed(evt);
            }
        });

        ChannelSearchButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        ChannelSearchButton.setText("Search");
        ChannelSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChannelSearchButtonActionPerformed(evt);
            }
        });

        ChannelLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        ChannelLabel2.setText("Search a Channel: ");

        ChannelSearchText.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        ChannelSearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChannelSearchTextActionPerformed(evt);
            }
        });

        ChannelDeleteButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        ChannelDeleteButton.setText("Delete");
        ChannelDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChannelDeleteButtonActionPerformed(evt);
            }
        });

        ChannelRefreshButton1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        ChannelRefreshButton1.setText("Refresh");
        ChannelRefreshButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChannelRefreshButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RightPaneLayout = new javax.swing.GroupLayout(RightPane);
        RightPane.setLayout(RightPaneLayout);
        RightPaneLayout.setHorizontalGroup(
            RightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightPaneLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(ChannelRefreshButton1)
                .addGap(18, 18, 18)
                .addComponent(ChannelSearchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(ChannelDeleteButton)
                .addGap(18, 18, 18)
                .addComponent(ChannelAddButton)
                .addGap(63, 63, 63))
            .addGroup(RightPaneLayout.createSequentialGroup()
                .addGroup(RightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightPaneLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RightPaneLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(ChannelListLabel))
                    .addGroup(RightPaneLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(RightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(RightPaneLayout.createSequentialGroup()
                                .addComponent(ChannelLabel2)
                                .addGap(0, 0, 0)
                                .addComponent(ChannelSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RightPaneLayout.createSequentialGroup()
                                .addComponent(ChannelLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(ChannelNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RightPaneLayout.setVerticalGroup(
            RightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightPaneLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ChannelListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(RightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChannelLabel1)
                    .addComponent(ChannelNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChannelLabel2)
                    .addComponent(ChannelSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(RightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChannelAddButton)
                    .addComponent(ChannelDeleteButton)
                    .addComponent(ChannelSearchButton)
                    .addComponent(ChannelRefreshButton1))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RightPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RightPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ChannelNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChannelNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChannelNameTextActionPerformed

    private void ChannelAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChannelAddButtonActionPerformed
        // TODO add your handling code here:
        String channelName = ChannelNameText.getText();
        Channel channel = new Channel(channelName);
        business.cl.addChannel(channel);
        JOptionPane.showMessageDialog(null,"Add Channel Successful");
        Populate();
    }//GEN-LAST:event_ChannelAddButtonActionPerformed

    
    private void Populate(){
        DefaultTableModel dtm = (DefaultTableModel) ChannelTable.getModel();
        dtm.setRowCount(0);
        for(Channel channel : business.cl.getChannelList()){
            Object[] row = new Object[1];
            row[0] = channel;
            dtm.addRow(row);
        }
    }
    
    private void ChannelSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChannelSearchButtonActionPerformed
        // TODO add your handling code here:
        String search = ChannelSearchText.getText();
        if(search != null){
            Channel c = business.cl.searchChannel(search);
            if(c != null){
                DefaultTableModel dtm = (DefaultTableModel) ChannelTable.getModel();
                dtm.setRowCount(0);
                Object[] row = new Object[1];
                row[0] = c;
                dtm.addRow(row);
            }
        }
    }//GEN-LAST:event_ChannelSearchButtonActionPerformed

    private void ChannelSearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChannelSearchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChannelSearchTextActionPerformed

    private void ChannelDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChannelDeleteButtonActionPerformed
        // TODO add your handling code here:
        int row = ChannelTable.getSelectedRow();
        if(row >= 0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete " +(Channel)ChannelTable.getValueAt(row, 0) + " channel?","Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                business.cl.DeleteChannel((Channel)ChannelTable.getValueAt(row, 0));
                Populate();
            }
        }else{
            JOptionPane.showMessageDialog(null,"Select a row!");
        }
    }//GEN-LAST:event_ChannelDeleteButtonActionPerformed

    private void ChannelRefreshButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChannelRefreshButton1ActionPerformed
        // TODO add your handling code here:
        Populate();
    }//GEN-LAST:event_ChannelRefreshButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChannelAddButton;
    private javax.swing.JButton ChannelDeleteButton;
    private javax.swing.JLabel ChannelLabel1;
    private javax.swing.JLabel ChannelLabel2;
    private javax.swing.JLabel ChannelListLabel;
    private javax.swing.JTextField ChannelNameText;
    private javax.swing.JButton ChannelRefreshButton1;
    private javax.swing.JButton ChannelSearchButton;
    private javax.swing.JTextField ChannelSearchText;
    private javax.swing.JTable ChannelTable;
    private javax.swing.JPanel RightPane;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
