/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package businessmanagement.userInterface;

import businessmanagement.Business.Business;
import businessmanagement.CustomerManagement.CustomerProfile;
import businessmanagement.MarketModel.Channel;
import businessmanagement.MarketModel.Market;
import businessmanagement.OrderManagement.Order;
import businessmanagement.ProductManagement.Product;
import businessmanagement.ProductManagement.SolutionOffer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 43999
 */
public class DealsForYouPane extends javax.swing.JPanel {

    /**
     * Creates new form DealsForYouPane
     */
    Business business;
    CustomerProfile customer;
    public DealsForYouPane(Business b, CustomerProfile cp) {
        initComponents();
        business = b;
        customer = cp;
        populateBundleTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BundleTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BundleProductTable = new javax.swing.JTable();
        AddToCartButton = new javax.swing.JButton();
        BuyButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        adButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setText("Deals For You!");

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setText("Bundles:");

        BundleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bundle Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BundleTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BundleTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(BundleTable);

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel3.setText("What's Inculude:");

        BundleProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Products", "Price", "Supplier"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(BundleProductTable);

        AddToCartButton.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        AddToCartButton.setText("Add to Cart");
        AddToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToCartButtonActionPerformed(evt);
            }
        });

        BuyButton.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        BuyButton.setText("Buy");
        BuyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel4.setText("New iPhone 12 pro is avilible now!");

        adButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessmanagement/userInterface/iPhone 12.jpg"))); // NOI18N
        adButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(191, 191, 191))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(adButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(AddToCartButton)
                            .addGap(221, 221, 221)
                            .addComponent(BuyButton))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(adButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddToCartButton)
                    .addComponent(BuyButton))
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BundleTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BundleTableMousePressed
        // TODO add your handling code here:
        int a = BundleTable.getSelectedRow();
        SolutionOffer so = (SolutionOffer) BundleTable.getValueAt(a, 0);
        populateBundleProductTable(so);
    }//GEN-LAST:event_BundleTableMousePressed

    private void AddToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToCartButtonActionPerformed
        // TODO add your handling code here:
        int a = BundleTable.getSelectedRow();
        if(a >= 0){
            SolutionOffer so = (SolutionOffer) BundleTable.getValueAt(a, 0);
            customer.getCart().addBundle(so);
            JOptionPane.showMessageDialog(null,"Bundle has been added to your cart!");
        }else{
            JOptionPane.showMessageDialog(null,"Please select a bundle!");
        }
    }//GEN-LAST:event_AddToCartButtonActionPerformed

    private void BuyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyButtonActionPerformed
        // TODO add your handling code here:
        int a = BundleTable.getSelectedRow();
        if(a >= 0){
            Market market = customer.getMarket();
            Channel channel = business.cl.searchChannel("Offical website");
            SolutionOffer so = (SolutionOffer)BundleTable.getValueAt(a, 0);
            Order order = new Order(market,channel,customer,null,so);
            business.mo.addOrder(order);
            customer.getOrderList().addOrder(order);
            JOptionPane.showMessageDialog(null,"Purchase successful! Your order number is: " + order.getNumber());
        }
    }//GEN-LAST:event_BuyButtonActionPerformed

    private void adButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adButtonActionPerformed
        // TODO add your handling code here:
        int yesNo = JOptionPane.showConfirmDialog(this,"Do you want to buy iPhone 12 Pro?", "Swing Tester",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
        if(yesNo == JOptionPane.YES_OPTION){
            Product product = business.pc.searchProductByName("iPhone 12 pro", 3);
            Market market = customer.getMarket();
            Channel channel = business.cl.searchChannel("Offical website");
            Order order = new Order(market,channel,customer,product,null);
            business.mo.addOrder(order);
            customer.getOrderList().addOrder(order);
            JOptionPane.showMessageDialog(null,"You have purchased " + product + ", your order number is: " + order.getNumber());
        }
    }//GEN-LAST:event_adButtonActionPerformed

    private void populateBundleTable(){
            DefaultTableModel dtm = (DefaultTableModel) BundleTable.getModel();
            dtm.setRowCount(0);
            for(SolutionOffer so : business.sc.getSolutionOfferList()){
                if(so.getMarket().equals(customer.getMarket())){
                    Object[] row = new Object[2];
                    row[0] = so;
                    row[1] = so.getPrice();
                    dtm.addRow(row);
                }
            }
    }
    
    private void populateBundleProductTable(SolutionOffer s){
        DefaultTableModel dtm = (DefaultTableModel) BundleProductTable.getModel();
        dtm.setRowCount(0);
        for(Product p : s.getProductBundle()){
            Object[] row = new Object[3];
            row[0] = p;
            row[1] = p.getPrice();
            row[2] = p.getSupplier();
            dtm.addRow(row); 
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCartButton;
    private javax.swing.JTable BundleProductTable;
    private javax.swing.JTable BundleTable;
    private javax.swing.JButton BuyButton;
    private javax.swing.JButton adButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
