/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package businessmanagement.userInterface;

import businessmanagement.Business.Business;
import businessmanagement.ProductManagement.Product;
import businessmanagement.ProductManagement.Supplier;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 43999
 */
public class SupplierDirectory extends javax.swing.JPanel {

    /**
     * Creates new form SupplierDirectory
     */
    Business business;
    Supplier supplier;
    public SupplierDirectory(Business b) {
        initComponents();
        business = b;
        populate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SupplierCatalogTable = new javax.swing.JTable();
        ViewProductsButton = new javax.swing.JButton();
        AddSupplierButton = new javax.swing.JButton();
        AddProductsButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        AddASupplierInputText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProductsTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        ProductNameInputText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ProductPriceInputText = new javax.swing.JTextField();
        ExpireDateInputText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        DeleteProductsButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setText("Supplier Direcotry");

        SupplierCatalogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Suppliers"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(SupplierCatalogTable);

        ViewProductsButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        ViewProductsButton.setText("View Products");
        ViewProductsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProductsButtonActionPerformed(evt);
            }
        });

        AddSupplierButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        AddSupplierButton.setText("Add Supplier");
        AddSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSupplierButtonActionPerformed(evt);
            }
        });

        AddProductsButton1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        AddProductsButton1.setText("Add Products");
        AddProductsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductsButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel2.setText("Add a Supplier: ");

        AddASupplierInputText.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        AddASupplierInputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddASupplierInputTextActionPerformed(evt);
            }
        });

        ProductsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Price", "ID", "Expire Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ProductsTable);

        jLabel4.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel4.setText("Product Name: ");

        ProductNameInputText.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel6.setText("Product Price: ");

        ProductPriceInputText.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N

        ExpireDateInputText.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel7.setText("Expire Date: ");

        DeleteProductsButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        DeleteProductsButton.setText("Delete Products");
        DeleteProductsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteProductsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddSupplierButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DeleteProductsButton)
                                .addGap(18, 18, 18)
                                .addComponent(ViewProductsButton)
                                .addGap(18, 18, 18)
                                .addComponent(AddProductsButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddASupplierInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ExpireDateInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProductPriceInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProductNameInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(260, 260, 260)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(ProductNameInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(AddASupplierInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ProductPriceInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ExpireDateInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddProductsButton1)
                    .addComponent(ViewProductsButton)
                    .addComponent(DeleteProductsButton)
                    .addComponent(AddSupplierButton))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewProductsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProductsButtonActionPerformed
        // TODO add your handling code here:
        int row = SupplierCatalogTable.getSelectedRow();
        if(row >= 0){
            supplier = (Supplier) SupplierCatalogTable.getValueAt(row, 0);
            populateProducts();
            
        }
    }//GEN-LAST:event_ViewProductsButtonActionPerformed

    private void populateProducts(){
        DefaultTableModel dtm = (DefaultTableModel) ProductsTable.getModel();
        dtm.setRowCount(0);
        for(Product product: business.sd.getSupplier(supplier).getProductCatalog().getProductCatalog()){
            Object[] row = new Object[4];
            row[0] = product;
            row[1] = product.getPrice();
            row[2] = product.getId();
            row[3] = product.getExpireDate();
            dtm.addRow(row);
        }
    }
    private void AddProductsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductsButton1ActionPerformed
        // TODO add your handling code here:
        int row = SupplierCatalogTable.getSelectedRow();
        if(row >= 0){
            supplier = (Supplier) SupplierCatalogTable.getValueAt(row, 0);
            try{
                String Name = ProductNameInputText.getText();
                double Price = Double.parseDouble(ProductPriceInputText.getText());
                String expireDate = ExpireDateInputText.getText();
                Product product = new Product(Name,Price,expireDate,supplier);
                supplier.getProductCatalog().addProduct(product);
                business.pc.addProduct(product);
            }catch(RuntimeException e){
                JOptionPane.showMessageDialog(null,"Price or ID must be number only!");
            }
            
            populateProducts();
        }else{
            JOptionPane.showMessageDialog(null,"Select a Supplier!");
        }
        
        
    }//GEN-LAST:event_AddProductsButton1ActionPerformed

    private void AddSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSupplierButtonActionPerformed
        // TODO add your handling code here:
        String supplier = AddASupplierInputText.getText();
        if(supplier.isEmpty() == false){
            Supplier s = new Supplier(supplier);
            business.sd.addSupplier(s);
            JOptionPane.showMessageDialog(null,"Add Successful");
            populate();
        }
        
    }//GEN-LAST:event_AddSupplierButtonActionPerformed

    private void populate(){
        DefaultTableModel dtm = (DefaultTableModel) SupplierCatalogTable.getModel();
        dtm.setRowCount(0);
        for(Supplier supplier : business.sd.getSupplierList()){
            Object[] row = new Object[1];
            row[0] = supplier;
            dtm.addRow(row);
        }
    }
    private void AddASupplierInputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddASupplierInputTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddASupplierInputTextActionPerformed

    private void DeleteProductsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteProductsButtonActionPerformed
        // TODO add your handling code here:
        int row = ProductsTable.getSelectedRow();
        int supplierRow = SupplierCatalogTable.getSelectedRow();
        supplier = (Supplier)SupplierCatalogTable.getValueAt(supplierRow,0);
        if(row >= 0){
            Product product = (Product) ProductsTable.getValueAt(row, 0);
            business.pc.deleteProdcut(product);
            supplier.getProductCatalog().deleteProdcut(product);
            populateProducts();
        }
    }//GEN-LAST:event_DeleteProductsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddASupplierInputText;
    private javax.swing.JButton AddProductsButton1;
    private javax.swing.JButton AddSupplierButton;
    private javax.swing.JButton DeleteProductsButton;
    private javax.swing.JTextField ExpireDateInputText;
    private javax.swing.JTextField ProductNameInputText;
    private javax.swing.JTextField ProductPriceInputText;
    private javax.swing.JTable ProductsTable;
    private javax.swing.JTable SupplierCatalogTable;
    private javax.swing.JButton ViewProductsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
