/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package businessmanagement.userInterface;

import businessmanagement.Business.Business;
import businessmanagement.CustomerManagement.CustomerProfile;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author 43999
 */
public class UserJFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserJFrame
     */
    static Business business;
    static CustomerProfile cp;
    public UserJFrame(Business b,CustomerProfile c) {
        initComponents();
        business = b;
        cp = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        LeftPane = new javax.swing.JPanel();
        PasswordButton = new javax.swing.JButton();
        OrderButton = new javax.swing.JButton();
        OrderListButton = new javax.swing.JButton();
        DealsButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        MyCartButton = new javax.swing.JButton();
        RightPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PasswordButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        PasswordButton.setText("Reset Password");
        PasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordButtonActionPerformed(evt);
            }
        });

        OrderButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        OrderButton.setText("Go Shopping!");
        OrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderButtonActionPerformed(evt);
            }
        });

        OrderListButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        OrderListButton.setText("My Orders");
        OrderListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderListButtonActionPerformed(evt);
            }
        });

        DealsButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        DealsButton.setText("Deals For You!");
        DealsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DealsButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        MyCartButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        MyCartButton.setText("My cart");
        MyCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyCartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftPaneLayout = new javax.swing.GroupLayout(LeftPane);
        LeftPane.setLayout(LeftPaneLayout);
        LeftPaneLayout.setHorizontalGroup(
            LeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPaneLayout.createSequentialGroup()
                .addGroup(LeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftPaneLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DealsButton))
                    .addGroup(LeftPaneLayout.createSequentialGroup()
                        .addGroup(LeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LeftPaneLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(LeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PasswordButton)
                                    .addGroup(LeftPaneLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(BackButton))
                                    .addGroup(LeftPaneLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(OrderListButton))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftPaneLayout.createSequentialGroup()
                                        .addComponent(OrderButton)
                                        .addGap(6, 6, 6))))
                            .addGroup(LeftPaneLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(MyCartButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LeftPaneLayout.setVerticalGroup(
            LeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackButton)
                .addGap(157, 157, 157)
                .addComponent(OrderButton)
                .addGap(31, 31, 31)
                .addComponent(DealsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(MyCartButton)
                .addGap(18, 18, 18)
                .addComponent(PasswordButton)
                .addGap(18, 18, 18)
                .addComponent(OrderListButton)
                .addGap(19, 19, 19))
        );

        SplitPane.setLeftComponent(LeftPane);

        javax.swing.GroupLayout RightPaneLayout = new javax.swing.GroupLayout(RightPane);
        RightPane.setLayout(RightPaneLayout);
        RightPaneLayout.setHorizontalGroup(
            RightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );
        RightPaneLayout.setVerticalGroup(
            RightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        SplitPane.setRightComponent(RightPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        UserLoginJFrame uljf = new UserLoginJFrame(business);
        uljf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void PasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordButtonActionPerformed
        // TODO add your handling code here:
        ResetPassWordPane rpwp = new ResetPassWordPane(cp);
        SplitPane.setRightComponent(rpwp);
    }//GEN-LAST:event_PasswordButtonActionPerformed

    private void OrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderButtonActionPerformed
        // TODO add your handling code here:
        GoShoppingPane gsp = new GoShoppingPane(business,cp);
        SplitPane.setRightComponent(gsp);
    }//GEN-LAST:event_OrderButtonActionPerformed

    private void DealsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DealsButtonActionPerformed
        // TODO add your handling code here:
        DealsForYouPane dfyp = new DealsForYouPane(business,cp);
        SplitPane.setRightComponent(dfyp);
    }//GEN-LAST:event_DealsButtonActionPerformed

    private void MyCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyCartButtonActionPerformed
        // TODO add your handling code here:
        CartPane cart = new CartPane(business,cp);
        SplitPane.setRightComponent(cart);
    }//GEN-LAST:event_MyCartButtonActionPerformed

    private void OrderListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderListButtonActionPerformed
        // TODO add your handling code here:
        MyOrdersPane mop = new MyOrdersPane(business,cp);
        SplitPane.setRightComponent(mop);
    }//GEN-LAST:event_OrderListButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserJFrame(business,cp).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton DealsButton;
    private javax.swing.JPanel LeftPane;
    private javax.swing.JButton MyCartButton;
    private javax.swing.JButton OrderButton;
    private javax.swing.JButton OrderListButton;
    private javax.swing.JButton PasswordButton;
    private javax.swing.JPanel RightPane;
    private javax.swing.JSplitPane SplitPane;
    // End of variables declaration//GEN-END:variables
}
